{% set name = "napari-skimage-regionprops" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-skimage-regionprops-{{ version }}.tar.gz
  sha256: a92af662061dad17e474fad26c895a55a83ef6462b0c90fd62648ed7125adb97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - pandas
    - python >=3.6
    - scikit-image

test:
  imports:
    - napari_skimage_regionprops
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-skimage-regionprops
  summary: A regionprops table widget plugin for napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
