{% set name = "napari-skimage-regionprops" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-skimage-regionprops-{{ version }}.tar.gz
  sha256: 79bf1c5057b2bf7a974a14eb7ea0e3e20522ce4e1b2e8d1bdc8e089f958ca162

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - pandas
    - python >=3.6
    - scikit-image
    - qtpy
    - toolz
    - typing_extensions
    - napari-workflows

test:
  imports:
    - napari_skimage_regionprops
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-skimage-regionprops
  summary: A regionprops table widget plugin for napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
